// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: key_generation/key_generation_service.proto

package key_generation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_generation_key_generation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_generation_key_generation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_generation_key_generation_service_proto_rawDescGZIP(), []int{0}
}

type GetKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_key_generation_key_generation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_generation_key_generation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_generation_key_generation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReallocateKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ReallocateKeyRequest) Reset() {
	*x = ReallocateKeyRequest{}
	mi := &file_key_generation_key_generation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReallocateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReallocateKeyRequest) ProtoMessage() {}

func (x *ReallocateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_generation_key_generation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReallocateKeyRequest.ProtoReflect.Descriptor instead.
func (*ReallocateKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_generation_key_generation_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReallocateKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReallocateKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ReallocateKeyResponse) Reset() {
	*x = ReallocateKeyResponse{}
	mi := &file_key_generation_key_generation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReallocateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReallocateKeyResponse) ProtoMessage() {}

func (x *ReallocateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_generation_key_generation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReallocateKeyResponse.ProtoReflect.Descriptor instead.
func (*ReallocateKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_generation_key_generation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReallocateKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReallocateKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_key_generation_key_generation_service_proto protoreflect.FileDescriptor

var file_key_generation_key_generation_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6b, 0x65, 0x79, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x6b, 0x65, 0x79, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6b,
	0x65, 0x79, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x47, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xad, 0x01, 0x0a, 0x0c, 0x4b, 0x65,
	0x79, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x43, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x58, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x22, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x52, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6b, 0x65, 0x79, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x3b,
	0x6b, 0x65, 0x79, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_key_generation_key_generation_service_proto_rawDescOnce sync.Once
	file_key_generation_key_generation_service_proto_rawDescData = file_key_generation_key_generation_service_proto_rawDesc
)

func file_key_generation_key_generation_service_proto_rawDescGZIP() []byte {
	file_key_generation_key_generation_service_proto_rawDescOnce.Do(func() {
		file_key_generation_key_generation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_key_generation_key_generation_service_proto_rawDescData)
	})
	return file_key_generation_key_generation_service_proto_rawDescData
}

var file_key_generation_key_generation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_key_generation_key_generation_service_proto_goTypes = []any{
	(*GetKeyRequest)(nil),         // 0: keygenerator.GetKeyRequest
	(*GetKeyResponse)(nil),        // 1: keygenerator.GetKeyResponse
	(*ReallocateKeyRequest)(nil),  // 2: keygenerator.ReallocateKeyRequest
	(*ReallocateKeyResponse)(nil), // 3: keygenerator.ReallocateKeyResponse
}
var file_key_generation_key_generation_service_proto_depIdxs = []int32{
	0, // 0: keygenerator.KeyGenerator.GetKey:input_type -> keygenerator.GetKeyRequest
	2, // 1: keygenerator.KeyGenerator.ReallocateKey:input_type -> keygenerator.ReallocateKeyRequest
	1, // 2: keygenerator.KeyGenerator.GetKey:output_type -> keygenerator.GetKeyResponse
	3, // 3: keygenerator.KeyGenerator.ReallocateKey:output_type -> keygenerator.ReallocateKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_generation_key_generation_service_proto_init() }
func file_key_generation_key_generation_service_proto_init() {
	if File_key_generation_key_generation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_key_generation_key_generation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_generation_key_generation_service_proto_goTypes,
		DependencyIndexes: file_key_generation_key_generation_service_proto_depIdxs,
		MessageInfos:      file_key_generation_key_generation_service_proto_msgTypes,
	}.Build()
	File_key_generation_key_generation_service_proto = out.File
	file_key_generation_key_generation_service_proto_rawDesc = nil
	file_key_generation_key_generation_service_proto_goTypes = nil
	file_key_generation_key_generation_service_proto_depIdxs = nil
}
