networks:
  textnest_dev_network:
    driver: bridge

services:
  key_generation_serivce:
    image: key_generation_service:latest
    restart: "no"
    environment:
      - PORT=:5055
      - HOST=localhost
      - DEVELOPMENT=true
      - REDIS_ADDR=host.docker.internal:6379
      - EXPIRATION_INTERVAL=5m
      - KAFKA_BROKER=localhost:9092
      - KAFKA_TOPICS=["delete-expired-key-topic", "user-notifications"]
      - KAFKA_RETRIES=5
    ports:
      - "5055:5055"
    networks:
      - textnest_dev_network


  upload_serivce:
    image: upload_service:latest
    restart: "no"
    environment:
      - PORT="4545"
      - HOST=localhost
      - DB_URL="postgres://textnest:password@localhost/metadata-dev-db?sslmode=disable"
      - S3_BUCKET_NAME=textnestbucket
      - S3_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=/run/secrets/aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=/run/secrets/aws_secret_access_key
    ports:
      - "4545:4545"
    networks:
      - textnest_dev_network
  
 
  download_service:
    image: download_service:latest
    restart: "no"
    environment:
      - PORT="7070"
      - HOST=localhost
      - DB_URL="postgres://textnest:password@localhost/metadata-dev-db?sslmode=disable"
      - METADATA_CACHE_REDIS_HOST=metadata_cache_redis
      - CONTENT_CACHE_REDIS_HOST=content_cache_redis
      - S3_BUCKET_NAME=textnestbucket
      - S3_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=/run/secrets/aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=/run/secrets/aws_secret_access_key
      - KAFKA_BROKER="9092"
      - EXPIRATION_INTERVAL=5m
      - KAFKA_RETRIES=5
    depends_on:
      - metadata_cache_redis
      - content_cache_redis
    ports:
      - "7070:7070"
    networks:
      - textnest_dev_network
  
  metadata_cache_redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6377:6379"
    networks:
      - textnest_dev_network
  
  content_cache_redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "6375:6379"
    networks:
      - textnest_dev_network

  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - textnest_dev_network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - textnest_dev_network

secrets:
  aws_access_key_id:
    external: true
  aws_secret_access_key:
    external: true

