grpc:
  port: ":4444"
kafka:
  brokers:
    - "localhost:9092"
  topics:
    - "delete-expired-key-topic"
bucket_name: "textnestbucket"
region: "eu-north-1"
db_url: "postgres://textnest:password@localhost/metadata-dev-db?sslmode=disable"
metadata_cache_addr: ":6379"
content_cache_addr: ":6380"
maxRetries: 5
expirationInterval: "5m"
