grpc:
  port: "50053"
kafka:
  brokers:
    - "kafka:9092"
  topics:
    - "delete-expired-paste-topic"
  groupID: "no-group"
  maxRetries: 5  

bucket_name: "textnestbucket"
region: "eu-north-1"
db: "postgres://textnest:textnest_password@postgres:5432/textnestdb?sslmode=disable"
metadata_cache_addr: ":6378"
content_cache_addr: ":6380"
expiration_interval: "5m"
