grpc:
  port: "50054"

redis: "redis:6379"

expirationInterval: "5m"

kafka:
  brokers:
    - "kafka:9092"
  topics:
    - "delete-expired-paste-topic"
  groupID: "no-group"
  maxRetries: 5  # Make sure this is a sensible value for your retries.

