// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: key_manager.proto

package key_manager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyManagerService_GetKey_FullMethodName        = "/keymanager.KeyManagerService/GetKey"
	KeyManagerService_ReallocateKey_FullMethodName = "/keymanager.KeyManagerService/ReallocateKey"
)

// KeyManagerServiceClient is the client API for KeyManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the service with only the required methods
type KeyManagerServiceClient interface {
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	ReallocateKey(ctx context.Context, in *ReallocateKeyRequest, opts ...grpc.CallOption) (*ReallocateKeyResponse, error)
}

type keyManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyManagerServiceClient(cc grpc.ClientConnInterface) KeyManagerServiceClient {
	return &keyManagerServiceClient{cc}
}

func (c *keyManagerServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerServiceClient) ReallocateKey(ctx context.Context, in *ReallocateKeyRequest, opts ...grpc.CallOption) (*ReallocateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReallocateKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagerService_ReallocateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyManagerServiceServer is the server API for KeyManagerService service.
// All implementations must embed UnimplementedKeyManagerServiceServer
// for forward compatibility.
//
// Define the service with only the required methods
type KeyManagerServiceServer interface {
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	ReallocateKey(context.Context, *ReallocateKeyRequest) (*ReallocateKeyResponse, error)
	mustEmbedUnimplementedKeyManagerServiceServer()
}

// UnimplementedKeyManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyManagerServiceServer struct{}

func (UnimplementedKeyManagerServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyManagerServiceServer) ReallocateKey(context.Context, *ReallocateKeyRequest) (*ReallocateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReallocateKey not implemented")
}
func (UnimplementedKeyManagerServiceServer) mustEmbedUnimplementedKeyManagerServiceServer() {}
func (UnimplementedKeyManagerServiceServer) testEmbeddedByValue()                           {}

// UnsafeKeyManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyManagerServiceServer will
// result in compilation errors.
type UnsafeKeyManagerServiceServer interface {
	mustEmbedUnimplementedKeyManagerServiceServer()
}

func RegisterKeyManagerServiceServer(s grpc.ServiceRegistrar, srv KeyManagerServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyManagerService_ServiceDesc, srv)
}

func _KeyManagerService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagerService_ReallocateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReallocateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServiceServer).ReallocateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagerService_ReallocateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServiceServer).ReallocateKey(ctx, req.(*ReallocateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyManagerService_ServiceDesc is the grpc.ServiceDesc for KeyManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keymanager.KeyManagerService",
	HandlerType: (*KeyManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _KeyManagerService_GetKey_Handler,
		},
		{
			MethodName: "ReallocateKey",
			Handler:    _KeyManagerService_ReallocateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key_manager.proto",
}
