db_url: "postgres://textnest:textnest_password@postgres:5432/textnestdb?sslmode=disable"
bucket_name: "textnestbucket"
expiration_interval: "1m"
kafka:
  brokers:
    - "kafka:9092"
  topics:
    - "delete-expired-paste-topic"
  groupID: "no-group"
  maxRetries: 5
