name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install dependencies & test (download_service 1)
        working-directory: services/download_service
        run: |
          go mod tidy
          go test ./...

      - name: Install dependencies & test (upload_service 2)
        working-directory: services/upload_service
        run: |
          go mod tidy
          go test ./...
