name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          version: 'latest'

      - name: Install dependencies & test (download_service 1)
        working-directory: services/download_service
        run: |
          go mod tidy
          # Start the required test containers (if any)
          docker run -d --name testcontainer my-test-image
          # Run tests
          go test ./tests
          # Optionally stop the container after tests
          docker stop testcontainer
          docker rm testcontainer

      - name: Install dependencies & test (upload_service 2)
        working-directory: services/upload_service
        run: |
          go mod tidy
          # Start the required test containers (if any)
          docker run -d --name testcontainer my-test-image
          # Run tests
          go test ./tests
          # Optionally stop the container after tests
          docker stop testcontainer
          docker rm testcontainer

